exports.seed = async function(knex) {
  await knex('projects').del()
  await knex('projects').insert([
    { name:'Sundarbans Mangrove Reserve', description:'UNESCO-listed mangrove delta protecting 10,000+ km² of coastal wetland.', location:'West Bengal, India', coordinates:'21.9497°N, 89.1833°E', area_sq_km:4262, validator_badge:'Verra', token_id:1001, target_credits:10000, issued_credits:8200, retired_credits:0, price_per_ton_usd:2850, ndvi_score:84, status:'active', created_at:new Date(), updated_at:new Date() },
    { name:'Bhitarkanika Coastal Forest', description:'Ramsar-designated wetland home to saltwater crocodiles and migratory birds.', location:'Odisha, India', coordinates:'20.7000°N, 86.9000°E', area_sq_km:672, validator_badge:'CCTS', token_id:1002, target_credits:7000, issued_credits:5100, retired_credits:0, price_per_ton_usd:2200, ndvi_score:76, status:'active', created_at:new Date(), updated_at:new Date() },
    { name:'Pichavaram Mangrove Block', description:'Second largest mangrove forest in the world with exceptional biodiversity.', location:'Tamil Nadu, India', coordinates:'11.4167°N, 79.7667°E', area_sq_km:42, validator_badge:'Gold Standard', token_id:1003, target_credits:5000, issued_credits:3400, retired_credits:0, price_per_ton_usd:1975, ndvi_score:71, status:'active', created_at:new Date(), updated_at:new Date() },
    { name:'Godavari Delta Reserve', description:'Rich river delta ecosystem spanning 729 km² of protected mangrove habitat.', location:'Andhra Pradesh, India', coordinates:'16.5000°N, 82.0000°E', area_sq_km:729, validator_badge:'Verra', token_id:1004, target_credits:9000, issued_credits:6700, retired_credits:0, price_per_ton_usd:3100, ndvi_score:79, status:'active', created_at:new Date(), updated_at:new Date() },
    { name:'Gulf of Mannar Marine Park', description:'Marine biosphere reserve with seagrass beds and coral reef carbon sinks.', location:'Tamil Nadu, India', coordinates:'9.2000°N, 79.1000°E', area_sq_km:560, validator_badge:'CCTS', token_id:1005, target_credits:4000, issued_credits:2100, retired_credits:0, price_per_ton_usd:1650, ndvi_score:65, status:'upcoming', created_at:new Date(), updated_at:new Date() },
    { name:'Chilika Lagoon Sanctuary', description:"Asia's largest coastal lagoon and winter home to Irrawaddy dolphins.", location:'Odisha, India', coordinates:'19.7167°N, 85.3167°E', area_sq_km:1165, validator_badge:'Gold Standard', token_id:1006, target_credits:3000, issued_credits:0, retired_credits:0, price_per_ton_usd:2400, ndvi_score:68, status:'soldout', created_at:new Date(), updated_at:new Date() },
  ])
  console.log('✅ 6 sample projects seeded')
}
